import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import { UserProvider } from "@/context/UserContext";
import RouteGuard from "@/components/RouteGuard";
import "@/app/globals.css";

const figtree = Figtree({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased `}>
        <UserProvider>
          <RouteGuard>{children}</RouteGuard>
        </UserProvider>
      </body>
    </html>
  );
}
