import type { Metadata } from "next";
import "@/app/globals.css";
import { Figtree } from "next/font/google";
import LicenseRegister from "@/synfusion-register";

const figtree = Figtree({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased `}>
        <LicenseRegister />
        {children}
      </body>
    </html>
  );
}
